### ISSUE TITLE
Error in parse_vector(x, col_factor(levels, ordered, include_na), na = na, : is.character(x) is not TRUE

### ISSUE THREAD

**Issue by philturk** [ropensci/qualtRics#113]
Hi Julia:

The function fetch_survey() keeps throwing a parse_vector error.  When I traced this, it seems it's related to a call to parse_factor() in the readr package?  (Interestingly, I can sometimes sneak a survey through by setting label = TRUE.)  I am aware that fetch_survey() calls read_survey() and that this same error popped up with the later function about a month ago, but that issue is still open.  

Any possibility of fixing this?  I'd be glad to help out :)

Best,

-- Phil

**Comment by juliasilge** [comment]
Thanks so much for checking in with this problem @philturk! 🙌  

Can you run the following code and then email me (my address is in the DESCRIPTION file) the CSV file at the path you find? It will be a fairly raw, unprocessed CSV file, but that is the one that is causing problems with `readr::read_csv()`, apparently!

```
root_url <- qualtRics:::append_root_url(Sys.getenv("QUALTRICS_BASE_URL"), "responseexports")
raw_payload <- qualtRics:::create_raw_payload(
    surveyID = <YOUR SURVEY ID HERE>,
    label = TRUE,
    last_response = NULL,
    start_date = NULL,
    end_date = NULL,
    unanswer_recode = NULL,
    limit = NULL,
    local_time = FALSE,
    include_questions = NULL
  )
res <- qualtRics:::qualtrics_api_request("POST", url = root_url, body = raw_payload)
ID <- res$result$id
survey.fpath <- qualtRics:::download_qualtrics_export(paste0(root_url, ID), verbose = TRUE)
survey.fpath
```

**Comment by philturk** [comment]
Hi Julia:

Thanks for your reply, Julia.  Let me work on coming up with a way to get you a CSV file from a data set that does not contain sensitive information.  This might take a couple days.

-- Phil

**Comment by philturk** [comment]
Hi Julia:

I just sent you a blinded CSV file that reproduces the error.

-- Phil

**Comment by juliasilge** [comment]
Thanks for sharing the CSV and your thoughts via email @philturk! The CSV reads just fine so that apparently is not the problem.

I am beginning to suspect that it is a problem in the [infer_data_types() function](https://github.com/ropensci/qualtRics/blob/ffd784c110da1c5caab31264cb5a85f543131a04/R/fetch_survey.R#L207). You can see where that function is [implemented here](https://github.com/ropensci/qualtRics/blob/ffd784c110da1c5caab31264cb5a85f543131a04/R/utils.R#L397). Especially notice the use of `reader::parse_factor()` in the [wrapper function for handling multiple choice functions](https://github.com/ropensci/qualtRics/blob/ffd784c110da1c5caab31264cb5a85f543131a04/R/utils.R#L481). Looks promising for being the source of this problem! 

Are you still getting this error, after updating to the latest versions on CRAN of tidyverse and qualtRics? Can you tell me if you get the error with both or just one of the following ways of using this package?

```r
survey1 <- fetch_survey(surveyID = <YOUR SURVEY ID>, convert = TRUE)
survey2 <- fetch_survey(surveyID = <YOUR SURVEY ID>, convert = FALSE)
```

**Comment by juliasilge** [comment]
I was just re-reading the email you sent me and notice that you mention the survey **metadata** containing columns/questions that are not in the actual **survey**. This makes sense as to the problem being located in `infer_data_types()`, which does call the [metadata](https://github.com/ropensci/qualtRics/blob/ffd784c110da1c5caab31264cb5a85f543131a04/R/utils.R#L402) to figure out what data types belong to each question.

Would you be able to send me the metadata for the survey CSV you sent me earlier? That contains the "extra" columns?

**Comment by philturk** [comment]
Hi Julia:

Sorry, I might not have been initially clear.  By metadata, I was referring to the metadata object created by the metadata.R function in the qualtRics package, not Qualtrics itself.  The original CSV file I sent you is complete.  

If you take the CSV file I sent you, work with that, and start tracing the thread backwards, we arrive at `infer_data-types()` inside utils.R.  With respect to lines 401-406, I will send you the metadata object under a separate email for your convenience.  At lines 407-440, a list object is created called `interest` using the metadata.  Notice that while it initially contains fourteen sub-lists corresponding to 14 questions, it ultimately is reduced to two two sub-lists corresponding to OrgType and Gender.  While these two variables somehow "make it through", their columns return NAs because they were not filled out in the original survey even though they are listed there alongside other variables.  Therefore, when they are passed to the readr function parse_factor() in line 483 of the wrapper_mc() function (see lines 466-492 in utils.R), we get the original error.

I hope I have been more clear this time.  If I have a moment later on, I will drill down into `interest` to see if I can uncover what is going on.  Thanks, Julia.

Best,

-- Phil

**Comment by juliasilge** [comment]
Today I rewrote [`infer_data_types()`](https://github.com/ropensci/qualtRics/blob/f31878cbcd97bc70e8f728e2b93a6f2b5aea9170/R/utils.R#L399) in a way that I *hope* solves this problem. 🤞 

Do you want to try installing this package from GitHub and then using `fetch_survey()` with `convert = TRUE`? You should no longer see the error.

```r
remotes::install_github("ropensci/qualtRics")
```

**Comment by philturk** [comment]
Yes, ma'am, that seems to have solved the problem.  I sincerely appreciate your following up on this.  See you at SDSS 🙂

**Comment by juliasilge** [comment]
🎉🎉🎉

**Comment by monicathieu** [comment]
Hi there,

I just transitioned to the new version of `qualtRics` after using the older version of Jasper's for the last year. Thanks for all your hard work, @juliasilge !

I was running into the same problem as indicated at the beginning of the issue, and changing my install to the github version of the package instead of the current CRAN version fixed it (yay!). However, this means that the CRAN version is due for an update as the package is functionally unusable for importing most of my surveys with that old `infer_data_types()` issue. Do you know when the package will be updated on CRAN? Flagging in case fellow re-installers run into this problem as well.

**Comment by juliasilge** [comment]
I'm so glad that the new version solves your problem! 🙌

I'm hoping to resolve a few issues such as #94 and #115 before submitting to CRAN again. Roughly, I'd estimate that this will all be finished in the next 2-3 months.

If you do need to use a CRAN-only package for some reason in the meantime, you could try using `convert = FALSE` and seeing if the results you get will work for your purposes.

**Comment by monicathieu** [comment]
Thanks for the update and the time estimate, Julia! (I understand you're maintaining this package pro bono so thank you SO MUCH.)

Weirdly, running `fetch_survey(convert = FALSE)` with the CRAN build of the package doesn't fix the issue for the surveys that I'm running into the problem with. I tried to do a little bit of triage to see what kinds of question types are throwing the error (as a couple of my surveys fetch fine with the CRAN build). I'm still not totally sure what the offending question type is, but it could have to do with matrix table or slider questions.
