### ISSUE TITLE
Error in fetch_survey with label = FALSE

### ISSUE THREAD

**Issue by vince-p** [ropensci/qualtRics#123]
For some surveys when I try to use the option 'label = FALSE' with the fetch_survey function I get the following error:
"Error in parse_vector(x, col_factor(levels, ordered, include_na), na = na,  : 
  is.character(x) is not TRUE"

Adding the option 'convert = FALSE' seems to fix this.

**Comment by juliasilge** [comment]
In commit f31878cbcd97bc70e8f728e2b93a6f2b5aea9170 there was a big rewrite of `infer_data_types()` that impacted the `label` and `convert` options. Do you get this error with the development version, or the CRAN version?

You can install the development version with:
```
install.packages("remotes")
remotes::install_github("ropensci/qualtRics")
```

**Comment by juliasilge** [comment]
It turns out that we need the labels from Qualtrics in order to do the conversion to factors, etc. This has also been discussed in #119. In commit 2090060996858346a0257da3959f319b691ccf87 I added some new condition checking and an error message to make sure folks don't try to use `label = FALSE` with `convert = TRUE`. You *can* use `convert = FALSE` with `label = TRUE`.

If you don't want to have labels, be sure to also not use the `convert` option:
```r
fetch_survey(my_id, label = FALSE, convert = FALSE)
```
