### ISSUE TITLE
fetch_survey does not capture very recent data

### ISSUE THREAD

**Issue by vince-p** [ropensci/qualtRics#124]
If I generate some test responses in qualtrics and then immediately try to run fetch_survey, it does not import the new responses. This is the case even with 'force_request = TRUE'.

I found a clue on this page: https://www.qualtrics.com/community/discussion/1888/qualtrics-api-export-missing-latest-results
It suggests that the API can capture very recent data by setting an end_date value.

This also works for fetch_survey BUT it only works if a different end_date is used for each request. I.e., the following is what happens:
1. If I generate test responses in qualtrics then try fetch_survey, the new responses are not captured.
2. If I set an end_date value for fetch_survey with a value in the future, the new data is imported.
3. If then generate more test data in qualtrics and try again to import using fetch_data, it does not capture the new data. This is true even if I use the same end_data value as step #2.
4. If I try with a new, different end_data value then the fetch_survey command does work.

**Comment by juliasilge** [comment]
Thanks for your patience with this @vince-p!

First off, I would just like to do a little screaming. 🙀What on earth kind of behavior is this; I MEAN REALLY.

OK, so where do we go from here? It seems like this is the **API** behavior, and not the R package per se. The R package supports the parameters that the API accepts, and it seems like changing those back and forth is how to get those very recent responses, if necessary.

I do have a call with a Qualtrics support person this coming week, and I'll bring this up. I don't believe there is much I can do from the R package side that will fix this, since it is the API behavior. Do you have any different ideas?

(I am feeling thankful that I don't have use cases where I need to see responses *immediately* right about now.)

**Comment by juliasilge** [comment]
We have recently moved to the newest API in #135 which I hope may solve issues like this one. Please open a new issue if you continue to have problems! 🙌
