### ISSUE TITLE
Error in parse_vector and qualtrics_response_codes(res)

### ISSUE THREAD

**Issue by bbherbert** [ropensci/qualtRics#128]
Hello!

I see that the following issue has been reported previously, but I have the most up to-date version of tidyverse.

```
 qualtrics_api_credentials(api_key = q_token, 
                          base_url = "pennstate.ca1.qualtrics.com",
                          install = FALSE)
surveys<-all_surveys()
screening<-fetch_survey(surveyID = "SV_2tzIFaj3nVW6tQF", label=FALSE, verbose = TRUE, convert = TRUE) 
```

returns 

```
Error in parse_vector(x, col_factor(levels, ordered, include_na), na = na,  : 
  is.character(x) is not TRUE
```

and
```
qualtrics_api_credentials(api_key = q_token, 
                          base_url = "pennstate.ca1.qualtrics.com",
                          install = FALSE)
surveys<-all_surveys()
screening<-fetch_survey(surveyID = "surveys[5]", label=FALSE, verbose = TRUE, convert = TRUE) 

```

returns

```
Error in qualtrics_response_codes(res) : 
  Qualtrics API raised a bad request (400) error - Please report this on
https://github.com/ropensci/qualtRics/issues
```

Please let me know how best to proceed!

**Comment by juliasilge** [comment]
Hello there, @bbherbert! Thanks for this report.

For the second option you have there, you don't want to put the survey ID into quotes, because then it gets passed as a string. You want to use `surveyID = surveys$id[5]`, **not** `surveyID = "surveys[5]"`.

It looks like you don't have the most recent version of qualtRics, because recently I have made more clear that you cannot use `label = FALSE` with `convert = TRUE` (we need the labels from Qualtrics in order to do the conversion to factors, etc). Can you make sure you have the most up-to-date version of qualtRics, and try your query again?

```r
install.packages("remotes")
remotes::install_github("ropensci/qualtRics")
```

Then try to download your survey with code such as:

```r
fetch_survey(my_id, label = FALSE, convert = FALSE)
```

**Comment by juliasilge** [comment]
The updated version of qualtRics is now on CRAN, so you should be able to just:

```r
install.packages("qualtRics")
```
And then download your survey with code such as shown above.
