### ISSUE TITLE
R 4.0 curl issue?

### ISSUE THREAD

**Issue by carlmcqueen** [ropensci/qualtRics#177]
On my non-upgraded computer the command: qualtRics::all_surveys() is still working just fine.

on my R 4.0 experimental version I keep getting this:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: https

tried installing from cran + github, same exact message.

**Comment by juliasilge** [comment]
A user had a similar problem in #173 and it ended being a problem in how they had saved their base URL. Can you check that out and make sure you have it saved correctly?

Notice that [when you register your credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials):

> The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`

**Comment by carlmcqueen** [comment]
This is exactly the sdame as #173 so it can be closed.

This is a change in the new version, before the qualtrics_api_credentials needed https:// now it's just the url without https.

I'll update all my code.

Thank you so much Julia.

**Comment by juliasilge** [comment]
This is really interesting that there is this difference between R 4.0 and previous, because nothing in the qualtRics code changed and we always intended for users to not include the scheme (http, https) so that we could handle that for the API. I haven't quite figured out what changed here!

Glad you are on your way, though. 👍
