### ISSUE TITLE
could the call to qualtrics_api_credentials happen in a test setup file?

### ISSUE THREAD

**Issue by maelle** [ropensci/qualtRics#198]
rather than in several test files?

Sorry if this is a naive question

**Comment by juliasilge** [comment]
This is not naive at all, and I just tried it. It turns out that some of the tests (quite of lot of them, it turns out) check setting and changing the credentials **themselves** so it didn't work out for me to set them once in a setup file. (The credentials would be different and not what we need after running the tests that would change the credentials, which are stored in environment variables.) 

I did, however, realize how silly it is to set the credentials over and over again multiple times in the same file, so I cleaned up the test files a bit. 🙌 It's an improvement, at least!!
