### ISSUE TITLE
`all_surveys` Error When Survey Name is Blank

### ISSUE THREAD

**Issue by Scott123456** [ropensci/qualtRics#212]
When running the `all_surveys` function, I get an error due to a `NULL` survey name. The error occurs when the function tries to `bind_rows(master)` at the end. It cannot complete the `bind_rows` if there is a null value in any of the elements. :/

I was able to work around it by changing the survey name in Qualtrics online. However, it took me a couple hours to figure out the issue. It's kind of crazy that Qualtrics returns an element with a null value (or even allows a survey to have no name), but it does and it breaks the expected behavior of the function.

One proposed solution is to check all elements for null values before appending or binding and replacing them with NA. Though I haven't been able to test this solution yet.

**Comment by juliasilge** [comment]
Oh, that sounds super frustrating, wow! 🥴 Your proposed solution sounds like a good thing to try here in the R package to get around the behavior in the API.

**Comment by jmobrien** [comment]
I noticed that `NULL`'s now no longer cause `bind_rows()` to fail; they just become `NA`'s.  I went looking for this to remember what was up--this is still open, but it looks like it's no longer relevant?  The underlying issue was fixed not long after in dplyr:  https://github.com/tidyverse/dplyr/pull/5502

I tested having a `NULL` survey name, and it's fine now.  Could open up options to simplify other code as well.
