### ISSUE TITLE
Error in `qualtrics_response_codes()`:

### ISSUE THREAD

**Issue by marcone84** [ropensci/qualtRics#268]
Hello, 
Received following error after trying to run all_surveys()...

> surveys <- all_surveys() 
Error in `qualtrics_response_codes()`:
! Qualtrics API raised a bad request (400) error - Please report this on
https://github.com/ropensci/qualtRics/issues

**Comment by juliasilge** [comment]
@maxsal It sounds like this might be a different problem; can you open a separate issue and create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. Thanks! 🙌

**Comment by juliasilge** [comment]
Hello @marcone84! There are two common issues that cause folks to run into this.

- The first is not having your base URL set correctly. Notice that [when you register your credentials](https://docs.ropensci.org/qualtRics/#register-your-qualtrics-credentials):

> The base URL you pass to the qualtRics package should either look like `yourdatacenterid.qualtrics.com` or like `yourorganizationid.yourdatacenterid.qualtrics.com`

- The second is Qualtrics proxying your request. Do you see any messages about this? For example, what do you see when you run this at the command line (not in R)?
 
```
curl --request GET \
--url https://conjoint.co1.qualtrics.com/API/v3/whoami \
--header 'x-api-token: YOURLONGAPITOKENHERE'
```

You would need to use _your_ URL and _your_ API token. Do you see anything in the results like:

> Notice: Request proxied. For faster response times, use this host instead:

If neither of these solve you problem, can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. Thanks! 🙌
