### ISSUE TITLE
Issue with the breakout_sets = FALSE` plus `label = FALSE`

### ISSUE THREAD

**Issue by hsinfei** [ropensci/qualtRics#289]
It worked just fine before, but now it is giving me an error:

Error: (converted from warning) Use caution with `breakout_sets = FALSE` plus `label = FALSE`
• Results will likely be incorrectly guessed and read in as numeric
• Use a `col_types` specification to override

The code is:

fetch_survey(surveyID = surveys$id[4], 
                      label = FALSE, convert = FALSE, verbose = TRUE, force_request = TRUE, breakout_sets = FALSE)

Can you un-do the change or suggesting a solution to this error?

**Comment by juliasilge** [comment]
Hmmmm, the code in qualtRics itself gives a warning only:

``` r
library(qualtRics)
my_survey <- 
  fetch_survey(
    surveyID = "SV_3gbwq8aJgqPwQDP", 
    breakout_sets = FALSE, 
    convert = FALSE, 
    label = FALSE
  )
#> Warning: Use caution with `breakout_sets = FALSE` plus `label = FALSE`
#> • Results will likely be incorrectly guessed and read in as numeric
#> • Use a `col_types` specification to override
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_double(),
#>   StartDate = col_datetime(format = ""),
#>   EndDate = col_datetime(format = ""),
#>   IPAddress = col_character(),
#>   RecordedDate = col_datetime(format = ""),
#>   ResponseId = col_character(),
#>   RecipientLastName = col_logical(),
#>   RecipientFirstName = col_logical(),
#>   RecipientEmail = col_logical(),
#>   ExternalReference = col_logical(),
#>   DistributionChannel = col_character(),
#>   UserLanguage = col_character(),
#>   Q19 = col_character(),
#>   Q22 = col_character(),
#>   FL_10_DO = col_logical()
#> )
#> ℹ Use `spec()` for the full column specifications.
```

<sup>Created on 2022-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

You say you are seeing "Error: (converted from warning)" which I expect means you have something else going on. 
Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this running in a clean session? The goal of a reprex is to make it easier for anyone to recreate your problem so that we can understand it and/or fix it. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. Thanks! 🙌

**Comment by hsinfei** [comment]
Thank you for the insights. I removed all the packages and keep the qualtRics only, and now it is working. Thank you so much!
