### ISSUE TITLE
Possible to update test fixture for `fetch_distributions()`?

### ISSUE THREAD

**Issue by juliasilge** [ropensci/qualtRics#293]
There was a recent release of vcr to CRAN that inadvertently caused test failures for folks who use vcr, including the [qualtRics tests](https://cran.r-project.org/web/checks/check_results_qualtRics.html). @sckott has been working hard 🙏 making updates to fix the situation, and we can get the current version of vcr via `devtools::install_github("ropensci/vcr")`. That fixes all our problems except the fixture for `fetch_distributions()`. You can read more in ropensci/vcr#255 but it looks like that fixture was recorded in a not-ideal way in terms of encoding.

I unfortunately don't have access to any distributions in the Qualtrics account I use so I am unable to regenerate it. 

@dsen6644, you recorded that fixture originally. Are you able to generate it again, using the current development version of vcr?

Or maybe @jmobrien, do you use distributions at all?

This is somewhat urgent as qualtRics has a Nov 20 deadline before getting booted off CRAN. Another alternative is to remove that test (and maybe just leave this issue open to regenerate it later when someone else is able to), although that would be a bummer.

**Comment by jmobrien** [comment]
I don't use distributions unfortunately, sorry.  But, looking at the fetch_distributions.yml fixture, I think there's something more going on:

The fixture (which dates back to March 8th, 2021) does have a different encoding than others (UTF-8 vs ASCII-8BIT for others).  But also, it's just empty--when the cassette is loaded and called, just returns `list()`.  

All the subsequent tests do pass, but that appears to be due to processing that happens after the API request [here](https://github.com/ropensci/qualtRics/blob/a55493b25ce079748a77ad973d22afc214fbe61e/R/fetch_distributions.R#L43-L83). 

I vaguely remember reading a discussion how this block of `purrr::map()` did something important--smoothing over idiosyncrasies in what came back from the endpoint or something?  But it looks like it might also be a little *too* forgiving?  It passes because the empty list gets turned into a zero-row, 34-column data frame.

All that said--I'm still getting up to speed on the *vcr* issue.  So I'm not sure what this says about how we should proceed.  But maybe this suggests we just should remove the test for now?   Not ideal, but given that the existing CRAN version already has problems with this test, removing it while we figure it out isn't  making anyone worse off.

**Comment by sckott** [comment]
for now you could just replace the string in `string` in that test fixture with the base64 encoded equivalent and that works for me locally at least. e.g., 

```r
z='{"result":{"elements":[],"nextPage":null},"meta":{"httpStatus":"200 - OK","requestId":"fa3cd279-8ad0-41e3-9d46-6c22ac6d31e3"}}'
base64enc::base64encode(charToRaw(z))
#> [1] "eyJyZXN1bHQiOnsiZWxlbWVudHMiOltdLCJuZXh0UGFnZSI6bnVsbH0sIm1ldGEiOnsiaHR0cFN0YXR1cyI6IjIwMCAtIE9LIiwicmVxdWVzdElkIjoiZmEzY2QyNzktOGFkMC00MWUzLTlkNDYtNmMyMmFjNmQzMWUzIn19"
```

**Comment by juliasilge** [comment]
Changed in dca81e2e10a06d0163abd1c80ae7199582969af7 but I think I want to leave this open so we can figure out what to do in the longer run

**Comment by juliasilge** [comment]
We have a new version on CRAN now which should solve our immediate issues. ✅ 

Let's actually close this issue in favor of #294, and figure out how to regenerate/correct all of these.
