### ISSUE TITLE
fetch_survey doesn't seem to pull a retaken response

### ISSUE THREAD

**Issue by vjbrady68** [ropensci/qualtRics#316]
I have a survey where I used Qualtrics' "retake response" feature and had a respondent retake their response after modifying their underlying embedded data. I can see the new response in the platform, but when I run fetch_surveys( force_request = T) I can only pull in the original response with the original embedded data. I contacted Qualtrics support and they can't seem to replicate the issue on their end. Any thoughts or suggestions about what might be going on?

**Comment by jmobrien** [comment]
Not immediately sure; I haven't encountered this before.  Question about what you're seeing on the web download; after retaking a response, does the data have a new row & response ID appended to the download (in addition to the original response?)  Or does it overwrite the original?  

Also, when Qualtrics said they couldn't replicate, you mean they said that their requests to the API produced the expected behavior (whatever it should be from the above)?   

Response fetching doesn't do a whole lot with what's returned from the API endpoint beyond putting it into the data frame, so I'm having a hard time imagining what (if anything) might be going wrong on our end.  Maybe if I hear a bit more about expected behavior something will come to mind.

Just to be clear, you're calling `fetch_surveys(<<surveyID>>, force_request = TRUE)`?  With no other arguments?

**Comment by vjbrady68** [comment]
Jmobrien, you know how when you're sick as soon as you make a dr's appointment whatever weird thing you had going on goes away? Well I just figured out what was going on. I was pulling the wrong version of the survey, we have a "Formal" and "Informal" version - and I was pulling the opposite one.

Thank you for such a speedy response though!!
