### ISSUE TITLE
Error in unz (colon in survey title)

### ISSUE THREAD

**Issue by higgi13425** [ropensci/qualtRics#345]
Apprently unable to connect/unzip a survey file with a colon in the title.
The survey is entitled 

Survey of Topics for Clinical Trials Academy 2: Running Your Own Trial

Code is 
my_survey <- fetch_survey(surveyID = 'SV_9Kw9QbuMrMyOoUC')
  |===============================================| 100%
Error in unz(description = zip_path, filename = csv_filename, open = "rb") : 
  cannot open the connection
In addition: Warning message:
In unz(description = zip_path, filename = csv_filename, open = "rb") :
  cannot open zip file '/var/folders/93/s18zkv2d4f556fxbjvb8yglc0000gp/T/RtmpAYTrax/file1835139200ab0.zip:Survey of Topics for Clinical Trials Academy 2'

This appears to cut off the path at the colon, so that it is an incorrect path.

Ideas on how to fix?

**Comment by juliasilge** [comment]
Ah yep, this is related to #329 and also #195. Since we have to deal with file paths on disk here in this R package and unzipping files, we can't handle special characters like `:` in survey titles. Eventually we would like to provide a way for you to change your survey title from R, but for now the workaround is for you to change your survey title in the Qualtrics UI. I know that is likely disappointing! 😞

**Comment by gdmcdonald** [comment]
Same issue, but the workaround of renaming the survey works fine. 👍

**Comment by higgi13425** [comment]
Originator of survey left employment - finally got someone in IT to change the title.
This did work
