### ISSUE TITLE
IP address?

### ISSUE THREAD

**Issue by WebCodeBox** [ropensci/qualtRics#346]
Hi everyone

When I call the qualtrics_api_credentials() command, the script not only wants to access the passed base_url, but the firewall also registers an access to this IP address: 20.208.63.39 .

According to ipinfo.io it belongs to Microsoft:
https://ipinfo.io/20.208.63.39

Can someone tell me why the library calls the IP address and what data is transmitted?
Are there any other IP addresses the package wants to connect which don't belong to Qualtrics?

Many thanks in advance
Kind regards
WebCodeBox

**Comment by juliasilge** [comment]
You can check out the code that `qualtrics_api_credentials()` runs here:

https://github.com/ropensci/qualtRics/blob/03f4b667133d58b1d655e89fd2361bfe6f1dbeb0/R/qualtrics_api_credentials.R#L47

Notice that it doesn't make any API calls or access any URLs including `base_url`; it only accesses your `.Renviron` file locally. When I run this function, it does not access any URLs. Seems like this is related to your system and how it access files rather than code run from the R package?

**Comment by WebCodeBox** [comment]
Thank you for your reply!
You are right.
The problem comes from Qualtrics and its IT infrastructure itself.
Qualtrics is using load balancing. And if you make API calls with different accounts, the IP address changes for every account.
At least I know at which point to tackle the problem.
