### ISSUE TITLE
Appveyor badge and webhook

### ISSUE THREAD

**Issue by maelle** [ropensci/qualtRics#79]
:wave: @JasperHG90!

* At the moment we no longer transfer Appveyor builds to ropensci account because it leads to more issues, so could you please re-update the badge in your README so that it points to https://ci.appveyor.com/project/JasperHG90/qualtrics-g2a4u ? Sorry about that!

* I've noticed that the [Appveyor webhook in this repo](https://github.com/ropensci/qualtRics/settings/hooks/14407959) is broken, latest deliveries have consistently failed. I've found several ropensci repos with the issue, including one of mine, and it seems to be random but you'll need to email Appveyor support team at  team@appveyor.com. They'll need to know this info about the latest delivery

    * X-GitHub-Delivery: b6641c60-5493-11e8-89a5-f00052f13186
    * Time: 2018-05-10 22:50:03

Thanks!

**Comment by maelle** [comment]
Maybe try that first (email received this night from Appveyor)

* New commit and push (the "account" was blocked, unclear to me whether they mean Appveyor or GitHub...)

*  If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 *   If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account.

**Comment by JasperHG90** [comment]
Hi @maelle :-)

I will do this as soon as I have some time (before end of the week). Thanks!

**Comment by maelle** [comment]
Thank _you_!

**Comment by JasperHG90** [comment]
Re-authorized GH and manually changed the repository under project settings. Builds are working again! Will update the badge now.

**Comment by JasperHG90** [comment]
FYI:

It's kind of weird but I noticed the following:

- The badge url (to the svg image) seems to migrate to ropensci just fine.

<img width="979" alt="badge" src="https://user-images.githubusercontent.com/8079803/40221144-dbf1b5d0-5a7b-11e8-9d64-08ef669d8447.png">

- The link to the appveyor build breaks because appveyor is looking for ropensci/qualtRics on its server, but the builds still happen on JasperHG90/qualtRics.

<img width="1017" alt="fail" src="https://user-images.githubusercontent.com/8079803/40221153-e131f654-5a7b-11e8-8aaf-af2268cb0163.png">

<img width="1032" alt="success" src="https://user-images.githubusercontent.com/8079803/40221158-e44f7a78-5a7b-11e8-9247-74e4d6a84e2d.png">

**Comment by maelle** [comment]
Yes sorry in the meantime @jeroen taught me that! Your badge should be sthg like

`[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/ropensci/opencage?branch=master&svg=true)](https://ci.appveyor.com/project/maelle/opencage)`

**Comment by maelle** [comment]
Thanks for your patience ☺

**Comment by JasperHG90** [comment]
No problem. Happy it's solved.
