### ISSUE TITLE
forceRequest --> still downloading to tempDir()

### ISSUE THREAD

**Issue by abrhim** [ropensci/qualtRics#80]
It seems that when I run the getSurvey() function with forceRequest = false it still downloads the survey straight to tempDir() then transfers it to the path I set in saveDir. I looked into getSurvey() documentation you have available at https://github.com/ropensci/qualtRics/blob/master/R/getSurvey.R and there is no if(forceRequest){save to saveDir}, the function only checks if there is anything is in saveDir. Do you have a fix for this issue? 

The only reason why I am interested in setting forceRequest=TRUE is because I have noticed that when I download larges batches data, say 10,000 rows, empty values are set to N/A and multiple columns are missing data entirely. While debugging I found the temp file saved in tempDir and it had none of the above errors. The quickest solution would be a forceRequest but ultimately I just want to download my data without any discrepancies.

**Comment by juliasilge** [comment]
Hello! 👋 I am the new maintainer of this package and I'm working on getting this package back on CRAN. I feel a bit unclear on what the problem was here, but is it in fact still a problem? 

Currently if a user has not set `force_request`, then the [function looks in the temp directory for `.rds` files](https://github.com/ropensci/qualtRics/blob/1ecbca4e0a87d0d266dfbbec563d74ff4938c46c/R/fetch_survey.R#L152) and returns what it finds. There is no downloading when `force_request = FALSE` and data exists already. If `force_request = FALSE` and there isn't any data found, then it's just like a brand new fetch of survey data.

Does that make sense? Is this issue outdated perhaps?

**Comment by abrhim** [comment]
Perhaps, me and my team are no longer using the library anymore so I am not longer able to really give good feedback on it.

**Comment by juliasilge** [comment]
Thanks for the quick response! I'll close this for now and we can revisit if other users have a similar problem.
