### ISSUE TITLE
Could not find function "qualtrics_register_options" when load the package "qualtRics".

### ISSUE THREAD

**Issue by Louis8102** [ropensci/qualtRics#91]
Dear Author of the package,
I followed the tutorial at https://quantdev.ssri.psu.edu/tutorials/using-qualtrics-and-boxr-r-packages
 to set API TOKEN and root_url info for authorization for downloading my survey data.
However, my R-studio prompts two messages as follows:

1) Error Message:
Error in qualtrics_register_options(verbose = verbose, useLabels = useLabels,  : 
  Cannot pass both base_url and root_url. Please use 'base_url' only.
In addition: Warning message:
In registerOptions(api_token = "dkLDk7Oy8i7430odW9kGOTl9FtvL5V0ljuctK1SC",  :
  'registerOptions' is deprecated and will be removed in version 4.0 of qualtRics.
Please use 'qualtrics_register_options' instead.
2)When I followed the instructions to use "base_url" and 'qualtrics_register_options' , the new message said that Could not find function "qualtrics_register_options" .

Hope you can help us!

Thank you!

**Comment by juliasilge** [comment]
Hello there @Louis8102! I am the new maintainer of this package. I know it's been a number of months since you posted this issue; thanks for your patience. 

This package is in a bit of flux right now and is not back on CRAN yet, but I wrote a new, simpler approach for using your Qualtrics credentials in R. If you can install from GitHub using the remotes package:

```
install.packages("remotes")
remotes::install_github("ropensci/qualtRics")
```

Then you can try using the new, simpler approach to handling API credentials:

```
library(qualtRics)
qualtrics_api_credentials(api_key = "<YOUR-QUALTRICS_API_KEY>", 
                          base_url = "<YOUR-QUALTRICS_BASE_URL>",
                          install = TRUE)
```

Check out the documentation for `qualtrics_api_credentials()`, and let me know if you have any problems!

**Comment by juliasilge** [comment]
@Louis8102 Let me know if you have other questions that come up!
